import nextPlugin from "@next/eslint-plugin-next";
import prettier from "eslint-config-prettier";
import tseslint from "typescript-eslint";

import { boundariesConfig } from "./eslint.boundaries.js";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/coverage/**",
      "**/playwright-report/**",
      "**/test-results/**",
      "**/next-env.d.ts",
      "design/**",
      // Generated by `supabase gen types`; its test compares it byte for byte with the CLI.
      "packages/db/src/database.types.ts",
      // Boundary fixtures break the rules on purpose. The core test lints them itself.
      "packages/core/test/fixtures/**",
    ],
  },
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/consistent-type-imports": "error",
    },
  },
  {
    // Config files and scripts live outside any tsconfig project.
    files: ["**/*.{js,mjs,cjs}"],
    ...tseslint.configs.disableTypeChecked,
  },
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    plugins: { "@next/next": nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
    },
    settings: { next: { rootDir: "apps/web" } },
  },
  {
    // A storage read link is made only by the accessor that signs it (#95), so a Manager
    // cannot hand a range read or a hash a URL of its own.
    files: ["packages/core/src/**/*.ts"],
    ignores: ["packages/core/src/Accessors/MediaStorageAccessor/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/MediaStorageAccessor/StorageReadLink"],
              importNames: ["issueStorageReadLink"],
              message:
                "Only MediaStorageAccessor issues a StorageReadLink. Ask it with OpenStorageReadRequest.",
            },
          ],
        },
      ],
    },
  },
  boundariesConfig,
  prettier,
);
